---
- name: Tomcat deployment playbook
  hosts: tomcat-nodes       # Inventory hosts group / server to act on
  become: yes               # If to escalate privilege
  become_method: sudo       # Set become method
  remote_user: ansadmin         # Update username for remote server
  vars:
    tomcat_ver: 9.0.30                          # Tomcat version to install
    ui_manager_user: manager                    # User who can access the UI manager section only
    ui_manager_pass: admin      # UI manager user password
    ui_admin_username: admin                    # User who can access bpth manager and admin UI sections
    ui_admin_pass: admin          # UI admin password
    tomcat_listen_address: 0.0.0.0
    tomcat_port_shutdown: 8005
    tomcat_port_connector: 8083
    tomcat_port_redirect: 8443
    tomcat_port_ajp: 8009
    tomcat_port_debug: 8000

    tomcat_ajp_enabled: False
    tomcat_ajp_listen_address: "::1"
    tomcat_ajp_secret: "my-@jp-s3cr3t"
    tomcat_ajp_secret_required: True  
  roles:
    - tomcat

